/**
 * genLyrics.ts — BUILD STEP. Reads the .kar, phonemises each syllable once, and
 * writes songLyrics.ts: an editable table of [timeMs, "text", "phonemes", midi].
 *
 * G2P is a build-time concern, not a runtime one, and its output should be an
 * artifact a human can correct by hand — French orthography is only ~90%
 * predictable and the misses are frequent words. Re-run to regenerate; hand
 * edits to songLyrics.ts are then the source of truth (don't overwrite lightly).
 *
 *   node genLyrics.ts <file.kar> [--out songLyrics.ts]
 */

import { writeFileSync } from "node:fs";
import { parseMidi } from "./midiParse.ts";
import { frenchSyllable } from "./g2p.ts";

const path = process.argv[2] ?? `${process.env.HOME}/Downloads/Patrick_singer_Qui_A_Le_Droit.mid`;
const outFile = process.argv.includes("--out") ? process.argv[process.argv.indexOf("--out") + 1] : "songLyrics.ts";

const song = parseMidi(path);
if (!song.lyrics.length) throw new Error(`${path} has no lyrics — not a .kar`);

const mel = song.notes.filter((n) => n.track === 3 && n.channel === 0).sort((a, b) => a.start - b.start);
const pitchAt = (t: number): number => {
  const sounding = mel.find((n) => t >= n.start - 0.05 && t < n.start + n.dur);
  if (sounding) return sounding.pitch;
  let best = mel[0];
  let bd = Infinity;
  for (const n of mel) {
    const d = Math.abs(n.start - t);
    if (d < bd) {
      bd = d;
      best = n;
    }
  }
  return best.pitch;
};

// a fragment ends a word if the NEXT syllable starts a new word (leading space)
// or a new line/paragraph, or there is no next one.
const rows: string[] = [];
let unknown = 0;
song.lyrics.forEach((l, i) => {
  const next = song.lyrics[i + 1];
  const wordEnd = !next || next.break !== "" || next.text.startsWith(" ");
  const ph = frenchSyllable(l.text, wordEnd);
  if (!ph.length) unknown++;
  const brk = l.break ? `, "${l.break}"` : "";
  const disp = l.text.replace(/"/g, '\\"');
  rows.push(`  [${Math.round(l.time * 1000)}, ${JSON.stringify(disp)}, ${JSON.stringify(ph.join(" "))}, ${pitchAt(l.time)}${brk}],`);
});

const header = `/**
 * songLyrics.ts — GENERATED by genLyrics.ts, then hand-correctable.
 *
 * Each row is one sung syllable:
 *   [ timeMs, "asWritten", "p h o n e m e s", midiPitch, break? ]
 *     timeMs   — onset from the .kar (the singer's own timing)
 *     phonemes — space-separated (see docs/voice.md); EDIT THESE to fix diction
 *     midi     — melody pitch sounding at that instant
 *     break    — "line" | "para" (optional), for phrasing/rests
 *
 * ${song.meta.filter((m) => m.startsWith("@T") || m.startsWith("@L")).join(" | ")}
 * ${song.lyrics.length} syllables, ${unknown} empty after G2P (marked "" — fix by hand).
 */

export type LyricRow = [number, string, string, number, ("line" | "para")?];

export const LYRICS: LyricRow[] = [
${rows.join("\n")}
];
`;

writeFileSync(outFile, header);
console.log(`wrote ${outFile}: ${song.lyrics.length} syllables (${unknown} need hand-fixing)`);
